version:  '3'
services:
  bitstation:
     image: "joequant/bitstation"
     build:
       context: 02.setup
       dockerfile: Dockerfile
       args:
          base: "joequant/cauldron"
     stdin_open: true
     tty: true
     ports:
       - 8082:8000
     devices:
       - /dev/fuse:/dev/fuse
     cap_add:
       - SYS_ADMIN

volumes:
   home:
