version:  '3'
services:
  bitstation:
     image: "joequant/bitstation"
     build:
       context: 02.setup
       dockerfile: Dockerfile
       args:
          base: "joequant/cauldron"
     stdin_open: true
     tty: true
     ports:
       - 8080:8000
     volumes:
       - home:/home

volumes:
   home:
